Expose libstdc++ for numpy based modules
This resolve binding with libstdc++ for numpy to properly work on the
nix environment:

```
Traceback (most recent call last):
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/numpy/_core/__init__.py",
line 22, in <module>
    from . import multiarray
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/numpy/_core/multiarray.py",
line 11, in <module>
    from . import _multiarray_umath, overrides
ImportError: libstdc++.so.6: cannot open shared object file: No such
file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/numpy/__init__.py",
line 112, in <module>
    from numpy.__config__ import show_config
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/numpy/__config__.py",
line 4, in <module>
    from numpy._core._multiarray_umath import (
    ...<3 lines>...
    )
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/numpy/_core/__init__.py",
line 48, in <module>
    raise ImportError(msg) from exc
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.13 from
"/home/sigmanificient/repos/ilo/lib_python/venv/bin/python"
  * The NumPy version is: "2.3.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: libstdc++.so.6: cannot open shared object file: No
such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File
"/home/sigmanificient/repos/ilo/lib_python/ilo/examples/alphabet.py",
line 1, in <module>
    import ilo
  File
"/home/sigmanificient/repos/ilo/lib_python/ilo/src/ilo/__init__.py",
line 1, in <module>
    from .ilo import (
    ...<6 lines>...
    )
  File "/home/sigmanificient/repos/ilo/lib_python/ilo/src/ilo/ilo.py",
line 25, in <module>
    import matplotlib
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/matplotlib/__init__.py",
line 161, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/matplotlib/cbook.py",
line 24, in <module>
    import numpy as np
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/numpy/__init__.py",
line 117, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy
from
        its source directory; please exit the numpy source tree, and
relaunch
        your python interpreter from there.
```