Add missing python dependencies for ilo
Theses runtimes libraries are required for the library to properly work,
so we should add them in the requirements:

```
Traceback (most recent call last):
  File
"/home/sigmanificient/repos/ilo/lib_python/ilo/examples/alphabet.py",
line 1, in <module>
    import ilo
  File
"/home/sigmanificient/repos/ilo/lib_python/ilo/src/ilo/__init__.py",
line 1, in <module>
    from .ilo import (
    ...<6 lines>...
    )
  File "/home/sigmanificient/repos/ilo/lib_python/ilo/src/ilo/ilo.py",
line 25, in <module>
    import matplotlib
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/matplotlib/__init__.py",
line 157, in <module>
    from packaging.version import parse as parse_version
ModuleNotFoundError: No module named 'packaging'
```

```
Traceback (most recent call last):
  File
"/home/sigmanificient/repos/ilo/lib_python/ilo/examples/alphabet.py",
line 1, in <module>
    import ilo
  File
"/home/sigmanificient/repos/ilo/lib_python/ilo/src/ilo/__init__.py",
line 1, in <module>
    from .ilo import (
    ...<6 lines>...
    )
  File "/home/sigmanificient/repos/ilo/lib_python/ilo/src/ilo/ilo.py",
line 16, in <module>
    from keyboard_crossplatform import KeyBordCrossPlatform
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/keyboard_crossplatform/__init__.py",
line 1, in <module>
    from .KeyboardCrossPlatform import KeyBordCrossPlatform
  File
"/home/sigmanificient/repos/ilo/lib_python/venv/lib/python3.13/site-packages/keyboard_crossplatform/KeyboardCrossPlatform.py",
line 90, in <module>
    import keyboard
ModuleNotFoundError: No module named 'keyboard'
```